name: Backend CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi "uvicorn[standard]" pydantic-settings sqlalchemy "psycopg[binary]" alembic pytest httpx ruff black isort

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Import order (isort)
        run: isort --check-only .

      - name: Tests
        run: python -m pytest -q


